### ISSUE TITLE
Sort e updates não funcionavam com tipagem dos parâmetros

### ISSUE THREAD

**Issue by jmurowaniecki** [doubleleft/hook-php#1]
Ao menos na minha versão PHP 5.5.14 o sort não funciona com a tipagem imposta.

**Comment by endel** [comment]
@jmurowaniecki rolava algum erro de PHP?

**Comment by jmurowaniecki** [comment]
@endel eu até havia esquecido disso /: mas acredito que estava resolvido lindamente igual (; bjbj
